name: Quality Control

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  GH_USER: ${{ secrets.GH_USER }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  validate:
    name: Validate
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - uses: caioreix/get-net-sdk-project-versions-action@v1
        id: get-version
        with:
          proj-path: vrising-utils.csproj
      - name: Check for Tag
        run: |
          TAG=${{steps.get-version.outputs.version}}
          if git show-ref --tags --verify --quiet "refs/tags/${TAG}"; then
            echo "Tag ${TAG} exists"
            exit 1
          else
            echo "Tag ${TAG} does not exist continuing..."
          fi

  test:
    name: Test
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Setup Source
        run: make source
      - name: Setup Source
        run: make test-release

  build:
    name: Build
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Setup Source
        run: make source
      - name: Setup Source
        run: make build-release
