name: Release Package

on:
  push:
    branches:
      - main

env:
  GH_USER: ${{ secrets.GH_USER }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  validate:
    name: Validate
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - uses: caioreix/get-net-sdk-project-versions-action@v1
        id: get-version
        with:
          proj-path: vrising-utils.csproj
      - name: Check for Tag
        run: |
          TAG=${{steps.get-version.outputs.version}}
          if git show-ref --tags --verify --quiet "refs/tags/${TAG}"; then
            echo "Tag ${TAG} exists"
            exit 1
          else
            echo "Tag ${TAG} does not exist continuing..."
          fi

  publish:
    name: Publish
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [ validate ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - uses: caioreix/get-net-sdk-project-versions-action@v1
        id: get-version
        with:
          proj-path: vrising-utils.csproj
      - name: Setup Source
        run: make source
      - name: Build
        run: make build-release
      - name: Publish
        run: dotnet nuget push "./dist/BepInEx-Utils.VRising.${{steps.get-version.outputs.version}}.nupkg" --api-key ${{ secrets.GH_TOKEN }} --source "https://nuget.pkg.github.com/caioreix/index.json"

  tag:
    name: Tag
    permissions:
      contents: write
    runs-on: ubuntu-latest
    needs: [ validate, publish ]

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3
      - uses: caioreix/get-net-sdk-project-versions-action@v1
        id: get-version
        with:
          proj-path: vrising-utils.csproj
      - uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{steps.get-version.outputs.version}}
